[build]
  base= "client"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "https://capston-aq-backend-production.up.railway.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
from = "/home"
to = "/"
status = 301



