export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Single} from "./Single"
export {default as Write} from "../Components/admin/Write"
export {default as About} from "./About"
export {default as Posts} from "./Posts"
export {default as Contact} from "./Contact"